### ISSUE TITLE
Add 22.40 to earlier versions

### ISSUE THREAD

**Issue by gnarl** [NetAppDocs/trident-2204#2]
Page: [Earlier versions of documentation](https://docs.netapp.com/us-en/trident-2204/earlier-versions.html)

Need to add link for 22.04 to this page. https://docs.netapp.com/us-en/trident-2204/trident-get-started/requirements.html

**Comment by juliantap** [comment]
Fixed with https://github.com/NetAppDocs/trident/pull/176
