### ISSUE TITLE
update the list of csi container images tag

### ISSUE THREAD

**Issue by udhayv** [NetAppDocs/trident-2204#3]
Page: [Requirements](https://docs.netapp.com/us-en/trident-2204/trident-get-started/requirements.html)

Note: trident-version: 22.04.0
*  in-doc: csi-snapshotter:v3.0.3 /run-time: csi-snapshotter:v5.0.1
* in-doc: csi-provisioner:v2.2.2 /run-time: csi-provisioner:v3.1.0

**Comment by juliantap** [comment]
Hi @udhayv, thank you for your feedback. I'm adding the team for confirmation.

@gnarl & @balaramesh can you confirm if I should make these changes on 22.04?

**Comment by gnarl** [comment]
Hi @juliantap,

Those changes aren't accurate for the csi-snapshotter and the 22.04.0 release. It looks like the provided information is [accurate for the 22.04.0 release](https://github.com/NetApp/trident/blob/stable/v22.04/cli/k8s_client/yaml_factory.go#L308) except for the information block at the bottom of the page. 

"use the validated k8s.gcr.io/sig-storage/csi-snapshotter:v4.x image only if the v1 version" can be updated to "use the validated k8s.gcr.io/sig-storage/csi-snapshotter:v5.x image only if the v1 version"

**Comment by juliantap** [comment]
Thank you, @gnarl. I've updated the note block and am merging it now. 

@udhayv this issue will auto-close when I merge the change detailed in the comment above. However, you can continue to comment on this if you have additional questions.
